### ISSUE TITLE
Different chip

### ISSUE THREAD

**Issue by Avinitlarge** [blark/a500plus-chipram-expansion#1]
I love this design but the chips used are a bit obscure. Big ask, could it be redesigned to use a more commonly available chip?

PRETTY PLEASE :D

**Comment by blark** [comment]
You can get the chips from utsource.

**Comment by Avinitlarge** [comment]
Shipping to the UK is nearly twice as much at the chips ☹️

**Comment by Avinitlarge** [comment]
Order 5 boards and 20 chips from UTsource, built 2 up and neither working in my 500+. Tried with 2 chip, 1 chip but nothing at all 😭

**Comment by Avinitlarge** [comment]
I’ve found 4 other chips that work with this now.

**Comment by blark** [comment]
Glad to hear that you got it working.
